### ISSUE TITLE
screw parser in shell

### ISSUE THREAD

**Issue by tankf33der** [chaos-lang/chaos#14]
latest master branch. easy level. iddqd.
gcc or clang.

```
$ uname -a
Linux lambda 5.4.18-1-MANJARO #1 SMP PREEMPT Thu Feb 6 11:41:30 UTC 2020 x86_64 GNU/Linux
$ make
$ ./chaos
Chaos Language 0.0.1-alpha (Feb 16 2020 23:49:06)                           
GCC version: 9.2.0 on linux                                                 
Turn chaos into magic!    
### bool v = true
### print v
true
### bool bool = bool
Parse error: syntax error
Line: 3
Cause: bool
free(): double free detected in tcache 2
Aborted (core dumped)
```
gg bb

```
$ gdb ./chaos core.9559 
GNU gdb (GDB) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./chaos...
(No debugging symbols found in ./chaos)
[New LWP 9559]
Core was generated by `./chaos'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fa9f7b3cf25 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007fa9f7b3cf25 in raise () from /usr/lib/libc.so.6
#1  0x00007fa9f7b26897 in abort () from /usr/lib/libc.so.6
#2  0x00007fa9f7b80258 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007fa9f7b8777a in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007fa9f7b8959d in _int_free () from /usr/lib/libc.so.6
#5  0x000055ef6ff224e5 in yydestruct ()
#6  0x000055ef6ff2519b in yyparse ()
#7  0x000055ef6ff25444 in main ()
(gdb) 
```

**Comment by mertyildiran** [comment]
@tankf33der I didn't have much time to mess with the parser for detecting false positives yet. Good catch! Gotta fix...

**Comment by mertyildiran** [comment]
@tankf33der this issue is no longer exists as of https://github.com/chaos-lang/chaos/commit/b843cd15d4cdbfcf7eec76da267bfc9622f57433
