### ISSUE TITLE
crash : array array = [1,2]

### ISSUE THREAD

**Issue by tankf33der** [chaos-lang/chaos#16]
clang, undefined sanitizer, x64, linux.

```
$ ./chaos
Chaos Language 0.0.1-alpha (Feb 17 2020 00:14:11)                           
Clang version: 9.0.1 on linux         
Turn chaos into magic!                                                      
### bool array = true
Parse error: syntax error
Line: 1
Cause: =
### print array
### array array = [1,2]
UndefinedBehaviorSanitizer:DEADLYSIGNAL
==10584==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address 0xfffffffffffffff9 (pc 0x7fa060e78470 bp 0x7ffd9c6961a0 sp 0x7ffd9c696120 T10584)
==10584==The signal is caused by a READ memory access.
    #0 0x7fa060e7846f in free (/usr/lib/libc.so.6+0x8b46f)
    #1 0x55669c5f0ccf in yydestruct (/home/mpech/chaos/chaos+0x5accf)
    #2 0x55669c5f02e3 in yyparse (/home/mpech/chaos/chaos+0x5a2e3)
    #3 0x55669c5f0f9e in main (/home/mpech/chaos/chaos+0x5af9e)
    #4 0x7fa060e14152 in __libc_start_main (/usr/lib/libc.so.6+0x27152)
    #5 0x55669c5b73bd in _start (/home/mpech/chaos/chaos+0x213bd)

UndefinedBehaviorSanitizer can not provide additional info.
==10584==ABORTING
```

**Comment by mertyildiran** [comment]
@tankf33der fixed with https://github.com/chaos-lang/chaos/commit/167c60a20172de520b11b4fedba02fa2f2b622e4
