### ISSUE TITLE
Segmentation fault on complex(array) as function parameter after scopes

### ISSUE THREAD

**Issue by mertyildiran** [chaos-lang/chaos#7]
**Describe the bug**
After https://github.com/chaos-lang/chaos/commit/d7c3f5feaecfa675bdf13b5646bc7128125cb026 we have introduced a bug to `functions.c` that causes Segmentation fault on complex(array) as function parameter:

```
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) file chaos
Reading symbols from chaos...done.
(gdb) run dev.kaos
Starting program: /usr/bin/chaos dev.kaos
first print this
inside function a
5
inside function b
8
true
5
hello my friend
false
3.14
hello my friend
hello world
3.14

Program received signal SIGSEGV, Segmentation fault.
__strcmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:174
174	../sysdeps/x86_64/multiarch/../strcmp.S: No such file or directory.
(gdb) bt
#0  __strcmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:174
#1  0x000055555555cfd7 in isDefined (name=0x697270202020200a <error: Cannot access memory at address 0x697270202020200a>) at symbol.c:249
#2  0x000055555555c67e in addSymbol (name=0x697270202020200a <error: Cannot access memory at address 0x697270202020200a>, type=FLOAT, value=...) at symbol.c:14
#3  0x000055555555ca2c in deepCopySymbol (symbol=0x555555779f20, key=0x697270202020200a <error: Cannot access memory at address 0x697270202020200a>) at symbol.c:109
#4  0x000055555555caff in deepCopyComplex (name=0x555555771050 "param2", symbol=0x55555577aeb0) at symbol.c:129
#5  0x000055555555d401 in createCloneFromSymbol (clone_name=0x555555771050 "param2", type=ARRAY, symbol=0x55555577aeb0, extra_type=ANY) at symbol.c:358
#6  0x000055555555b86b in callFunction (name=0x55555577cc30 "f2") at functions/function.c:69
#7  0x0000555555555fbc in yyparse () at chaos.y:88
#8  0x00005555555587aa in main (argc=2, argv=0x7fffffffde48) at chaos.y:453
(gdb) quit
A debugging session is active.

	Inferior 1 [process 16379] will be killed.

Quit anyway? (y or n) y
```

**To Reproduce**

Run this program file with `chaos dev.kaos`:

```
void func a()
    print "inside function a"
    num val1 = 5
    print val1
end

print "first print this"

a()
b()

null function b()
    print "inside function b"
    num val2 = 8
    print val2
end

str hello = 'hello world'
number pi = 3.14

str param1 = 'test1'

nil def f1(bool param1, num param2, str param3)
    param3 = 'hello my friend'
    print param1
    print param2
    print param3
end

f1(true, 5, hello)
f1(false, pi, "OMG!")

print hello
print pi

array c = [1, 2, 3]

array def f2(string param1, array param2)
    print param1
    return param2
end

print f2('Array function parameter:', c)

dict d = {'a': 'foo', 'b': 'bar', 'c': 'baz'}

dict func f3(string param1, dict param2)
    print param1
    return param2
end

print f3('Dictionary function parameter:', d)

num def add(num x, num y)
    num result = x + y
    return result
end

print add(3, 5)

```
Modifiying `f1` function like below conceals the bug:

```
nil def f1(bool param1, num param2, str param3)
    param3 = 'hello my friend'
    print param1
    print param2
    print param3
    symbol_table
end
```

OR

```
nil def f1(bool param1, num param2, str param3)
    print "hey"
    param3 = 'hello my friend'
    print param1
    print param2
    print param3
end
```

There is probably a deep memory issue that somewhere, maybe not even related to functions or scopes implementation.

**Expected behavior**
Output to be:

```
first print this
inside function a
5
inside function b
8
hey
true
5
hello my friend
hey
false
3.14
hello my friend
hello world
3.14
Array function parameter:
[1, 2, 3]
Dictionary function parameter:
{'a': 'foo', 'b': 'bar', 'c': 'baz'}
8
```

**Environment:**
 - CPU Architecture: `x86_64`
 - Operating System - Distro : Version/Build: `Linux - Ubuntu : 18.04`
 - C Compiler Name and Version: `gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0`
 - Chaos Language Version: `Chaos Language 0.0.1-alpha (Jan 21 2020 22:53:21)`

**Comment by mertyildiran** [comment]
Fixed with:
 - https://github.com/chaos-lang/chaos/commit/1e075a945d2c6203c7175f30f2074ed18d7fd019
 - https://github.com/chaos-lang/chaos/commit/313f58f1a4ba8627573a0dd4556f25207f7862f3

Proven to be working:
 - https://github.com/chaos-lang/chaos/commit/1f7003e6d89ba192a3fa0c226719fa88786d8235
