### ISSUE TITLE
Segmentation fault on undefined function call

### ISSUE THREAD

**Issue by mertyildiran** [chaos-lang/chaos#8]
**Describe the bug**
Undefined function call causes Segmentation fault in both interactive shell and program file.

**To Reproduce**
```
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) file chaos
Reading symbols from chaos...done.
(gdb) run
Starting program: /usr/bin/chaos 
    Chaos Language 0.0.1-alpha (Feb  5 2020 02:33:17)                           
    GCC version: 7.4.0 on linux                                                 
    Turn chaos into magic!                                                      

### a()

Program received signal SIGSEGV, Segmentation fault.
0x000055555555bfa2 in callFunction (name=0x555555787440 "a") at functions/function.c:74
74	    for (int i = 0; i < function->parameter_count; i++) {
(gdb) bt
#0  0x000055555555bfa2 in callFunction (name=0x555555787440 "a") at functions/function.c:74
#1  0x0000555555556117 in yyparse () at chaos.y:98
#2  0x0000555555558ad6 in main (argc=1, argv=0x7fffffffd7b8) at chaos.y:470
(gdb) 
```

**Expected behavior**
An error should be thrown.

**Environment:**
 - CPU Architecture: `x86_64`
 - Operating System - Distro : Version/Build: `Linux - Ubuntu : 18.04`
 - C Compiler Name and Version: `gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0`
 - Chaos Language Version: `Chaos Language 0.0.1-alpha (Jan 21 2020 22:53:21)`

**Comment by mertyildiran** [comment]
Fixed with https://github.com/chaos-lang/chaos/commit/c7c6d2dc4b11fbedd13fdede5850ec2d0b47dcd6
