### ISSUE TITLE
crash on empty input

### ISSUE THREAD

**Issue by tankf33der** [chaos-lang/chaos#9]
**Describe the bug**
crash

**To Reproduce**
```
$ make clean
$ make
$ ./chaos
    Chaos Language 0.0.1-alpha (Feb  7 2020 16:26:08)                           
    GCC version: 9.2.0 on linux                                                 
    Turn chaos into magic!                                                      

### <press Ctrl-D>
```

**Environment:**
 - CPU Architecture: x86_64
 - Operating System - Distro : Manjaro Linux
 - C Compiler Name and Version: gcc v9.2.0
 - Chaos Language Version: latest master

**Additional context**
```
$ gdb ./chaos core.17093 
GNU gdb (GDB) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./chaos...
[New LWP 17093]
Core was generated by `./chaos'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f8b732206f5 in __strlen_avx2 () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007f8b732206f5 in __strlen_avx2 () from /usr/lib/libc.so.6
#1  0x00007f8b732c072d in ?? () from /usr/lib/libreadline.so.8
#2  0x00005583c28f6677 in shell_readline (buf=0x5583c2e82b40 "(null)\n") at utilities/shell.c:95
#3  0x00005583c28f26b8 in custom_input (buf=0x5583c2e82b40 "(null)\n", result=0, max_size=8192) at chaos.l:45
#4  0x00005583c28f3bb8 in yy_get_next_buffer () at lex.yy.c:1343
#5  0x00005583c28f36eb in yylex () at lex.yy.c:1183
#6  0x00005583c28ef814 in yyparse () at chaos.tab.c:1677
#7  0x00005583c28f2444 in main (argc=1, argv=0x7ffec5011768) at chaos.y:470
(gdb) 
```

**Comment by mertyildiran** [comment]
Hi @tankf33der I'm so thankful to you for your contributions as an issue reporter and tester. Pull requests are also highly welcomed if you consider to send any.

The bug has been fixed with https://github.com/chaos-lang/chaos/commit/c83898f63d4eec4c2606ff55ad1e14764a8c5c85

**Comment by tankf33der** [comment]
Did you get my email from yesterday that make and make clean are broken? :)

btw, i ported chaos to solaris 11 sparc. In general all working except several failed tests, more issues are coming.

**Comment by mertyildiran** [comment]
@tankf33der I'm sorry I didn't see your mail until now. My school email inbox is a mess :smile: 

I'm responding now...
